# Generated by cpp11: do not edit by hand

forest_mat <- function(x, depths, vars, thresh) {
  .Call(`_bases_forest_mat`, x, depths, vars, thresh)
}

dist_l2 <- function(x, y) {
  .Call(`_bases_dist_l2`, x, y)
}

dist_l1 <- function(x, y) {
  .Call(`_bases_dist_l1`, x, y)
}
