# Generated by cpp11: do not edit by hand

forest_mat <- function(x, depths, vars, thresh) {
  .Call(`_bases_forest_mat`, x, depths, vars, thresh)
}

dist_l2 <- function(x, y) {
  .Call(`_bases_dist_l2`, x, y)
}

dist_l1 <- function(x, y) {
  .Call(`_bases_dist_l1`, x, y)
}

im2col <- function(x, h, w, c, size, stride) {
  .Call(`_bases_im2col`, x, h, w, c, size, stride)
}

mult_partition <- function(n, k) {
  .Call(`_bases_mult_partition`, n, k)
}

row_prod <- function(x) {
  .Call(`_bases_row_prod`, x)
}
